### ISSUE TITLE
Reversing even further

### ISSUE THREAD

**Issue by AppleTechy** [jeroenmoors/php-ring-api#1]
I have been poking around even further into their API and discovered they are using SIP to stream the feed. Though I can only seem to intercept SIP authentication when someone rings the doorbell but not when I initiate live view. Have you done any poking into trying to get the actual video feed?

👍  On your authentication. I had just been planning on using one of the authentication tokens I intercepted from my devices as those never seem to expire/reset. Though your Authentication allows for the user not to have to intercept the token, rather just get an assigned one.

**Comment by jeroenmoors** [comment]
Sorry for the very late reply! I've not yet experimented with the video-feeds.

Are you able to get the SIP feed working? Which client do you use to show the SIP video?

**Comment by AppleTechy** [comment]
No worries! Unfortunately I haven't been able to get the SIP feeds to work correctly. I have tried using an online JavaScript To access the SIP but it doesn't show the video feed. Someone I was working with on this tried using the LifeSize Cloud app for iOS, but also didn't have any luck getting it to display the feeds
