### ISSUE TITLE
Waiting for response form webserver

### ISSUE THREAD

**Issue by janwbouma** [jeroenmoors/php-ring-api#3]
Hi,

Thanks for this API for the RING.com doorbell.

I've tried use it on a apache webserver.
I've add my credentials to the example.php file and try to access it through the browser.
After a few minutes it still waiting for a response without printing a message on the screen.

Are you familiare with this? I opened all the firewall ports listed on: https://support.ring.com/hc/en-us/articles/205385394-What-Ports-Do-I-Need-to-Open-in-My-Firewall-for-Ring-Doorbells-and-Chimes-

Hope you can help me out.

Kind Regard, Jan Willem

**Comment by ghost** [comment]
Same here. Just "Authenticating...". What are we missing?

**Comment by jeroenmoors** [comment]
You can't run the script via a webserver. It should be  executed from the command line as it will run forever.

There's a infinitive loop in which every 5 seconds is checked if somebody pressed your doorbell.

Try to run it like:
php example.php
