### ISSUE TITLE
PHP Warning:  Invalid argument supplied for foreach() in /home/andreas/Downloads/php-ring-api-master/ring.php on line 96

### ISSUE THREAD

**Issue by pixiandreas** [jeroenmoors/php-ring-api#5]
When i run the example file. after add change to my username and passwd i got this:

PHP Warning:  Invalid argument supplied for foreach() in /home/andreas/Downloads/php-ring-api-master/ring.php on line 96

The authenticating works as it should. 

If i run this in chrome
Call: https://api.ring.com/clients_api/dings/active?api_version=9&auth_token=zzbGBjWFcvCZKArwFQfH
The only i got is this.
[ ]

**Comment by rossdargan** [comment]
@pixiandreas I hope that auth token isn't valid...

**Comment by Doudy** [comment]
I have the same problem

> Call: https://api.ring.com/clients_api/dings/active?api_version=9&auth_token=mytoken

> **PHP Warning:  Invalid argument supplied for foreach() in /home/pi/php-ring-api-master/ring.php on line 96**

When i run this in chrome : https://api.ring.com/clients_api/dings/active?api_version=9&auth_token=mytoken
I have a correct answer : 

> {"doorbots":[{"id":123456,"description":"Porte de devant","device_id":"f12ae235687","time_zone":"Europe/Brussels", ......

an idea ?
thanks

**Comment by IanMitchell77** [comment]
I get this too, help!

Well, it says line 95 for me.

**Comment by 7ooL** [comment]
I have the same issue.
Warning: Invalid argument supplied for foreach() in ring.php on line 98

**Comment by jeroenmoors** [comment]
I've pushed a new version, this should fix the foreach issue.

**Comment by pixiandreas** [comment]
Working ok, when i run forsome hours but then the same eror again , a restart solving the problem.

Oct 06 09:49:16 hass php[16695]: PHP Warning:  Invalid argument supplied for foreach() in /home/andreas/scripts/php-ring
Oct 06 09:49:19 hass php[16695]: PHP Warning:  Invalid argument supplied for foreach() in /home/andreas/scripts/php-ring
Oct 06 09:49:23 hass php[16695]: PHP Warning:  Invalid argument supplied for foreach() in /home/andreas/scripts/php-ring
Oct 06 09:49:27 hass php[16695]: PHP Warning:  Invalid argument supplied for foreach() in /home/andreas/scripts/php-ring
