### ISSUE TITLE
no devices or pushes or motion detection

### ISSUE THREAD

**Issue by IanMitchell77** [jeroenmoors/php-ring-api#6]
When I run the example it prints

My devices:
string(0) ""

then polls but never says anything.
It authenticates and gets a token:

Authenticating...
Authenticated as Ian Mitchell
Authentication token is QokMAmTPFqQRwL9FcGxz

This worked yesterday.

I get rings in the ring app on my phone and it shows the events on the ring website.

Yesterday this worked but I had lots of trouble and the support guy told me to exchange it, I did and now things seem to work much nicer, apart from this php script.

Thanks in advance for any help!

**Comment by jeroenmoors** [comment]
Sorry for the very late reply. Do you still have this issue?

**Comment by 10der** [comment]
issues still here
http://pastexen.com/i/6VO2AuVu8S.png
