### ISSUE TITLE
401 Unauthorized?

### ISSUE THREAD

**Issue by sjhill01** [jeroenmoors/php-ring-api#7]
Authentication works fine, but polling results in a 401 response. Are you still running this code? Does it work for others? Thanks for your efforts at putting this together!

**Comment by blysik** [comment]
Same as issue https://github.com/homespun/homebridge-platform-ring-video-doorbell/issues/16

**Comment by jeroenmoors** [comment]
Sorry for the very late reply!

I had a similar issue and got it resolved by changing (by a random value) the last digit of the hardware id at https://github.com/jeroenmoors/php-ring-api/blob/master/ring.php#L67

**Comment by jeroenmoors** [comment]
Just pull the current code, it should resolve this issue.
